### ISSUE TITLE
Assign new role upon register

### ISSUE THREAD

**Issue by sweggggg** [saqueib/roles-permissions-laravel#1]
I've notice that if new user is registered, their default role is "User" role

My question is, how to I automatically change its default roles upon register?

**Comment by saqueib** [comment]
You can change the role on the register to any role you wanted by changing [Auth\RegisterController@create](https://github.com/saqueib/roles-permissions-laravel/blob/master/app/Http/Controllers/Auth/RegisterController.php#L72) method. 

```php
protected function create(array $data)
    {
        $user = User::create([
            'name' => $data['name'],
            'email' => $data['email'],
            'password' => bcrypt($data['password']),
        ]);

        // assign user role
        $user->assignRole('User'); // change the role you wanted to assign here
        return $user;
    }
```

This method creates the user and later I have added the role for the default user.

**Comment by sweggggg** [comment]
wow it works fine, but the problem is the new user have 2 roles now which is the default role and the assigned role

how do i completely change its default role?

*edit*

so i just solved it by adding $user->removeRole('User');

is there any better way beside this solution?

thank you in advanced @saqueib

**Comment by saqueib** [comment]
you can sync roles, which will delete all the roles and assign given role, just change the line to this

```php
$user->syncRoles('User'); // It will give user only User role
```
