### ISSUE TITLE
Error in PermissionRegistrar

### ISSUE THREAD

**Issue by oterox** [saqueib/roles-permissions-laravel#2]
Just cloned the repo, ran composer install and then on the browser:
FatalErrorException in PermissionRegistrar.php line 33:
syntax error, unexpected ':', expecting ';' or '{'

Any idea?

**Comment by saqueib** [comment]
I have tried reproducing this but its no error for me. You can follow this steps it should work:

1. Clone the repo
2. Run `composer install`
3. Run cp `cp .env.example .env`
4. run `php artisan key:generate`
5. edit db credential in .env
6. Now run `php artisan db:seed`

then if you serve your app using `php artisan serve` it should work. 
If this doesn't work, make sure you have correct permissions, directories within the `storage` and the `bootstrap/cache` directories should be writable by your web server. Also, run composer update if required

**Comment by saqueib** [comment]
Its turnout the PHP version of is very old, you need PHP >= 5.6.4 to run, but PHP 7 will be best. Please update the php and it will work.
