### ISSUE TITLE
FatalErrorException in /vendor/spatie/laravel-permission/src/PermissionRegistrar.php line 33: syntax error, unexpected ':', expecting ';' or '{'

### ISSUE THREAD

**Issue by sundarocs** [saqueib/roles-permissions-laravel#3]
Hi,
I am getting this error. Can you please advise?
FatalErrorException in /vendor/spatie/laravel-permission/src/PermissionRegistrar.php line 33: syntax error, unexpected ':', expecting ';' or '{'

**Comment by saqueib** [comment]
Already answered #2, it is due to old version of php, you need PHP 5.6 or higher to run Laravel 5.4
