### ISSUE TITLE
migrate errors

### ISSUE THREAD

**Issue by nabi009** [saqueib/roles-permissions-laravel#4]
when I use "php artisan migrate" so it gives error
 [Illuminate\Database\QueryException]                                                                                                                                   
  SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name '' (SQL: create table `` (`id` int unsigned not null auto_increment primary key, `name`   
  varchar(191) not null, `guard_name` varchar(191) not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate utf8mb4_un  
  icode_ci)  
[PDOException]                                                                   
  SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name ''

**Comment by saqueib** [comment]
It's very late reply, but I think you missed to publish the config.

```
php artisan vendor:publish --provider="Spatie\Permission\PermissionServiceProvider" --tag="config"
```

This should fix it
