### ISSUE TITLE
The DatabaseSeeder

### ISSUE THREAD

**Issue by Fatih90** [saqueib/roles-permissions-laravel#5]
Why not creating a seperate seeders to keep things clear and make it more readable like
UsersTableSeeder
RolesTableSeeder
PermissionsTableSeeder
PostsTableSeeder

**Comment by saqueib** [comment]
I wanted to give option to specify roles when seeding
> Create Roles for user, default is admin and user?  

where you can pass comma separated list of roles to create them.

But yes it's a good idea to keep every tables seeder in separate seeder classes. I will update it very soon or you could PR that will be fantastic

**Comment by Fatih90** [comment]
yea i tried to create seperate seeders but i failed because of
