### ISSUE TITLE
erron db:seed

### ISSUE THREAD

**Issue by pedroreartes** [saqueib/roles-permissions-laravel#6]
Hi!
I follow the intructions:
clone repo
set .env
and when I try db:seed ->
PHP Fatal error:  require(): Failed opening required 'rpl/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/php') in rpl/bootstrap/autoload.php on line 17
PHP Stack trace:
PHP   1. {main}() rpl/artisan:0
PHP   2. require() rpl/artisan:16
whats happening?
thanks!!!

**Comment by saqueib** [comment]
You need to install composer dependency buy running 

`composer install`
